[mongodb]
mongodb.kranthi86s.fun

[redis]
redis.kranthi86s.fun
    
[mysql]
mysql.kranthi86s.fun

[rabbitmq]
rabbitmq.kranthi86s.fun

[catalogue]
catalogue.kranthi86s.fun

[cart]
cart.kranthi86s.fun

[user]
user.kranthi86s.fun

[shipping]
shipping.kranthi86s.fun

[payment]
payment.kranthi86s.fun

[frontend]
frontend.kranthi86s.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=kranthi86s