[mongodb]
172.31.3.103

[redis]
172.31.6.215

[mysql]
172.31.9.119

[rabbitmq]
172.31.8.49

[catalogue]
172.31.12.118

[cart]
172.31.3.78

[user]
172.31.2.189

[shipping]
172.31.2.189

[payment]
172.31.11.75

[frontend]
172.31.9.108

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=kranthi Kumar