- name: install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql
- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: move jar file
  command: mv /opt/app/target/ /opt/app/payment.kranthi.fun -- -{{ version }}.jar shipping.kranthi.fun.jar
  args:
    chdir: /app